### ISSUE TITLE
Absolute paths to dependencies break Yocto build

### ISSUE THREAD

**Issue by patrislav1** [ChimeraTK/meta-chimeratk#6]
[`PROJECT_NAMEConfig.cmake.in.in`](https://github.com/ChimeraTK/project-template/blob/master/cmake/PROJECT_NAMEConfig.cmake.in.in#L101) exports absolute paths to its project's dependencies in `@PROJECT_NAME@_LIBRARIES`. This does not necessarily work in BitBake/Yocto world, where the root prefix of a dependency package (such as `/path/to/yocto/project/.../tmp/work/<arch>/<package>/.../recipe-sysroot`) is different from the depending package. When the depending package tries to access the root prefix of the dependency's build environment, it can fail in many ways, for instance when a [sstate cache](https://docs.yoctoproject.org/overview-manual/concepts.html?#shared-state-cache) is shared between projects, or when it is built on the target.

I made a [patch for the DeviceAccess recipe](https://github.com/ChimeraTK/meta-chimeratk/commit/e0a41bd86c914de0916eb252e0f633ac97f1269a) which replaces the absolute paths by just the filenames of the dependency libraries. This works for now, but may not be enough. There are probably all projects affected that use [project-template](https://github.com/ChimeraTK/project-template). Maybe it should be fixed upstream instead of patching every project that uses it. OTOH, there may be the odd project that actually requires the full path to a library at a exotic location, so this may break other things in turn.

**Comment by phako** [comment]
We have exotic install locations usually everywhere in the development environment. Have to check how we can make that somewhat more streamlined / better / ... 

I kinda was hoping that we can get rid of that problem with the imported targets though

**Comment by patrislav1** [comment]
CMake `bbclass` passes a few env variables to the build where the CMake script could infer the sysroot and strip it from the paths. This would be quite universal and wouldn't change behavior on non-Yocto/Bitbake builds. Maybe `PKG_CONFIG_SYSROOT_DIR` or `LD` (the `--sysroot` part) would be good candidates for this?

```bash
🐳 yocto a791419e6098 build # env | grep "recipe-sysroot\s*$"
CXX=aarch64-xilinx-linux-g++  -mcpu=cortex-a72.cortex-a53 -march=armv8-a+crc -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Wdate-time --sysroot=/mnt/yocto/damc_ds5014dr_test_project/prj/yocto/build/tmp/work/cortexa72-cortexa53-xilinx-linux/deviceaccess/03.11.00-r0/recipe-sysroot
CXXFLAGS= -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/mnt/yocto/damc_ds5014dr_test_project/prj/yocto/build/tmp/work/cortexa72-cortexa53-xilinx-linux/deviceaccess/03.11.00-r0=/usr/src/debug/deviceaccess/03.11.00-r0                      -fdebug-prefix-map=/mnt/yocto/damc_ds5014dr_test_project/prj/yocto/build/tmp/work/cortexa72-cortexa53-xilinx-linux/deviceaccess/03.11.00-r0=/usr/src/debug/deviceaccess/03.11.00-r0                      -fdebug-prefix-map=/mnt/yocto/damc_ds5014dr_test_project/prj/yocto/build/tmp/work/cortexa72-cortexa53-xilinx-linux/deviceaccess/03.11.00-r0/recipe-sysroot=                      -fdebug-prefix-map=/mnt/yocto/damc_ds5014dr_test_project/prj/yocto/build/tmp/work/cortexa72-cortexa53-xilinx-linux/deviceaccess/03.11.00-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden  -mcpu=cortex-a72.cortex-a53 -march=armv8-a+crc -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Wdate-time  --sysroot=/mnt/yocto/damc_ds5014dr_test_project/prj/yocto/build/tmp/work/cortexa72-cortexa53-xilinx-linux/deviceaccess/03.11.00-r0/recipe-sysroot
CCLD=aarch64-xilinx-linux-gcc  -mcpu=cortex-a72.cortex-a53 -march=armv8-a+crc -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Wdate-time --sysroot=/mnt/yocto/damc_ds5014dr_test_project/prj/yocto/build/tmp/work/cortexa72-cortexa53-xilinx-linux/deviceaccess/03.11.00-r0/recipe-sysroot
LD=aarch64-xilinx-linux-ld --sysroot=/mnt/yocto/damc_ds5014dr_test_project/prj/yocto/build/tmp/work/cortexa72-cortexa53-xilinx-linux/deviceaccess/03.11.00-r0/recipe-sysroot 
PKG_CONFIG_SYSROOT_DIR=/mnt/yocto/damc_ds5014dr_test_project/prj/yocto/build/tmp/work/cortexa72-cortexa53-xilinx-linux/deviceaccess/03.11.00-r0/recipe-sysroot
FC=aarch64-xilinx-linux-gfortran  -mcpu=cortex-a72.cortex-a53 -march=armv8-a+crc -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Wdate-time --sysroot=/mnt/yocto/damc_ds5014dr_test_project/prj/yocto/build/tmp/work/cortexa72-cortexa53-xilinx-linux/deviceaccess/03.11.00-r0/recipe-sysroot
CC=aarch64-xilinx-linux-gcc  -mcpu=cortex-a72.cortex-a53 -march=armv8-a+crc -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Wdate-time --sysroot=/mnt/yocto/damc_ds5014dr_test_project/prj/yocto/build/tmp/work/cortexa72-cortexa53-xilinx-linux/deviceaccess/03.11.00-r0/recipe-sysroot
CFLAGS= -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/mnt/yocto/damc_ds5014dr_test_project/prj/yocto/build/tmp/work/cortexa72-cortexa53-xilinx-linux/deviceaccess/03.11.00-r0=/usr/src/debug/deviceaccess/03.11.00-r0                      -fdebug-prefix-map=/mnt/yocto/damc_ds5014dr_test_project/prj/yocto/build/tmp/work/cortexa72-cortexa53-xilinx-linux/deviceaccess/03.11.00-r0=/usr/src/debug/deviceaccess/03.11.00-r0                      -fdebug-prefix-map=/mnt/yocto/damc_ds5014dr_test_project/prj/yocto/build/tmp/work/cortexa72-cortexa53-xilinx-linux/deviceaccess/03.11.00-r0/recipe-sysroot=                      -fdebug-prefix-map=/mnt/yocto/damc_ds5014dr_test_project/prj/yocto/build/tmp/work/cortexa72-cortexa53-xilinx-linux/deviceaccess/03.11.00-r0/recipe-sysroot-native=   -mcpu=cortex-a72.cortex-a53 -march=armv8-a+crc -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Wdate-time  --sysroot=/mnt/yocto/damc_ds5014dr_test_project/prj/yocto/build/tmp/work/cortexa72-cortexa53-xilinx-linux/deviceaccess/03.11.00-r0/recipe-sysroot
```

We could also add something like `EXTRA_OECMAKE = "-DBB_SYSROOT=${RECIPE_SYSROOT}"` to each recipe, if we don't want to infer the sysroot like this.

**Comment by phako** [comment]
Ah wait. Nothing should be using that. If something is still using that, it needs to be ported to imported targets. This is just for the backwards compatibility of not-yet-ported projects.

It could be that this also leaks into pkg-config, but I already have a ticket in redmine to fix the pkg-config files

**Comment by patrislav1** [comment]
Yes, the absolute library paths created by `create_cmake_config_files.cmake` also show up in the `.pc` files. IIRC, my workaround patch also fixes those.

**Comment by phako** [comment]
OK, so this is basically redmine issue #11493 which aims to fix the pkg-config stuff by properly using $prefix and $sysroot - the cmake things i'd just ignore IMHO. Although we need to update our documentation to make clear that imported targets are the preferred way to consume ChimeraTK in CMake

**Comment by patrislav1** [comment]
No, this bug also leaks the dependency's build environment sysroot to `@PROJECT_NAME@_LIBRARIES` which is imported when using CMake `FindPackage(...)` in the dependent project. The `create_cmake_config_files.cmake` actually [resolves the CMake target of the library to an absolute path](https://github.com/ChimeraTK/project-template/blob/e906920d26c00c90aafce23b4339a3cfb2cf9fc9/cmake/create_cmake_config_files.cmake#L103C70-L103C70) and [exports it to `@PROJECT_NAME@_LIBRARIES`](https://github.com/ChimeraTK/project-template/blob/e906920d26c00c90aafce23b4339a3cfb2cf9fc9/cmake/create_cmake_config_files.cmake#L186).

**Comment by patrislav1** [comment]
see here for example:

```bash
huesmann@mskpcx29856  ~/src/yocto/petra_motion_control/prj/yocto/build/tmp/work/aarch64-xilinx-linux/deviceaccess/03.11.00-r0  ↱ main  grep recipe-sysroot sysroot-destdir/usr/lib/cmake/ChimeraTK-DeviceAccess/ChimeraTK-DeviceAccessConfig.cmake
set(ChimeraTK-DeviceAccess_INCLUDE_DIRS /home/mskfw/jenkins_fw/workspace/_petra_petra_motion_control_main/prj/yocto/build/tmp/work/aarch64-xilinx-linux/deviceaccess/03.11.00-r0/recipe-sysroot/usr/include /usr/include)
set(ChimeraTK-DeviceAccess_LIBRARIES ${ChimeraTK-DeviceAccess_LIBRARIES} -lChimeraTK-DeviceAccess -lrt /home/mskfw/jenkins_fw/workspace/_petra_petra_motion_control_main/prj/yocto/build/tmp/work/aarch64-xilinx-linux/deviceaccess/03.11.00-r0/recipe-sysroot/usr/lib/libboost_thread.so.1.71.0 -lpthread /home/mskfw/jenkins_fw/workspace/_petra_petra_motion_control_main/prj/yocto/build/tmp/work/aarch64-xilinx-linux/deviceaccess/03.11.00-r0/recipe-sysroot/usr/lib/libboost_system.so.1.71.0 /home/mskfw/jenkins_fw/workspace/_petra_petra_motion_control_main/prj/yocto/build/tmp/work/aarch64-xilinx-linux/deviceaccess/03.11.00-r0/recipe-sysroot/usr/lib/libboost_chrono.so.1.71.0 /home/mskfw/jenkins_fw/workspace/_petra_petra_motion_control_main/prj/yocto/build/tmp/work/aarch64-xilinx-linux/deviceaccess/03.11.00-r0/recipe-sysroot/usr/lib/libboost_filesystem.so.1.71.0 -latomic)
```
(this is BTW a nice example for what happens when BitBake pulls packages from a shared sstate mirror and the dependency paths point to a path on a whole different machine)

on my PC it is similar (also all absolute paths):
```bash
 huesmann@mskpcx29856  ~/src/ctk/DeviceAccess/build   master  grep DeviceAccess_LIBRARIES ChimeraTK-DeviceAccessConfig.cmake
#   ChimeraTK-DeviceAccess_LIBRARIES    : libraries the depending project needs to link against
            set(ChimeraTK-DeviceAccess_LIBRARIES ${ChimeraTK-DeviceAccess_LIBRARY} ${ChimeraTK-DeviceAccess_LIBRARIES})
set(ChimeraTK-DeviceAccess_LIBRARIES ${ChimeraTK-DeviceAccess_LIBRARIES} -lChimeraTK-DeviceAccess -lrt /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.71.0 /usr/lib/x86_64-linux-gnu/libboost_atomic.so.1.71.0 -lpthread /usr/lib/x86_64-linux-gnu/libboost_system.so.1.71.0 /usr/lib/x86_64-linux-gnu/libboost_chrono.so.1.71.0 /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.71.0 -latomic)
```

In an earlier version of ProjectTemplate, it exported actual CMake targets of the dependencies, not their absolute paths. Here an example for DeviceAccess V2.05:
```bash
 huesmann@mskpcx29856  ~/src/ctk/DeviceAccess/build   master  grep DeviceAccess_LIBRARIES /usr/local/lib/cmake/ChimeraTK-DeviceAccess/ChimeraTK-DeviceAccessConfig.cmake 
#   ChimeraTK-DeviceAccess_LIBRARIES    : libraries the depending project needs to link against
  set(ChimeraTK-DeviceAccess_LIBRARIES ${ChimeraTK-DeviceAccess_LIBRARY} Boost::thread;Boost::system;Boost::chrono;Boost::filesystem /usr/lib/x86_64-linux-gnu/libatomic.so.1 -lrt -lpthread)
  set(ChimeraTK-DeviceAccess_LIBRARIES Boost::thread;Boost::system;Boost::chrono;Boost::filesystem /usr/lib/x86_64-linux-gnu/libatomic.so.1 -lrt -lpthread)
```

**Comment by phako** [comment]
Does that really break something? They should not be used AT ALL by our software and if it is, we need to change that. They are still provided as long as we do not have ported everything to CMake imported targets.

And we need to document that no-one should be using that when using CMake. And at some point remove it completely. The imported target fixes exactly that problem.

This here should be used instead when using ChimeraTK::ChimeraTK_DeviceAccess

INTERFACE_LINK_LIBRARIES "-lrt;Boost::thread;Boost::system;Boost::chrono;Boost::filesystem;ChimeraTK::ChimeraTK-cppext"

**Comment by patrislav1** [comment]
Yes, it breaks [DeviceAccess-PythonBindings](https://github.com/ChimeraTK/DeviceAccess-PythonBindings/blob/8ed26fd336d3010a508a09f1dbd1e801840a8ff6/CMakeLists.txt#L120), for example.

Is there a example project with a CMake file that makes it a bit more clear how to properly consume ChimeraTK packages now?

**Comment by patrislav1** [comment]
Oh I see the recent version doesn't use `_LIBRARIES` anymore. Maybe we just need to bump the version in the `deviceaccess-python-bindings` recipe?

**Comment by patrislav1** [comment]
Tried to bump the `deviceaccess-python-bindings` version from 03.01 to 03.02 for the updated CMake file, but then the patches wouldn't apply anymore ...

**Comment by phako** [comment]
I will check.

**Comment by phako** [comment]
There is now an honister branch with all latest and greatest

**Comment by patrislav1** [comment]
Thanks! Will check ASAP and close this if it's resolved.

**Comment by patrislav1** [comment]
With current `deviceaccess-python-bindings` this issue is resolved. Thanks again!

**Comment by phako** [comment]
There was an issue with open65423 (also fixed) but I suppose you usually do not build that

**Comment by patrislav1** [comment]
it's this OPC UA library, right? No, I didn't use it yet
