### ISSUE TITLE
qthardmon adds dependency on meta-qt5 layer

### ISSUE THREAD

**Issue by moto-timo** [ChimeraTK/meta-chimeratk#7]
https://layers.openembedded.org/layerindex/updates/38566/

For both `honister` and `kirkstone` branches, the `qthardmon` recipe inherits `cmake_qt5` which is provided by the `meta-qt5` layer, but this layer is not listed as a LAYERDEPENDS.

https://github.com/ChimeraTK/meta-chimeratk/blob/honister/recipes-tools/qthardmon/qthardmon_01.07.00.bb#L15

**Comment by phako** [comment]
Probably needs some kind of distroconfig or somesuch to be properly optional?

**Comment by moto-timo** [comment]
You can't parse classes you don't have present (hence the error in Layer Index update). So if you want this to be optional, the recipe should be in a dynamic-layers/qt5-layer instead. And then you could put qt5-layer in LAYERRECOMMENDS.

**Comment by phako** [comment]
@moto-timo Can you have  quick look in #8 if I understood the documentation correctly?

**Comment by moto-timo** [comment]
Confirmed both 'honister' and 'kirkstone' are no longer showing the layerindex issue. Thank you.
